### ISSUE TITLE
OS busy when shutting bot down

### ISSUE THREAD

**Issue by RDIL** [RDIL/cakebot#27]
Control + C throws following error:
```none
------------
Ready to roll, I'll see you on Discord: @Cakebot#5394
------------
Loading formatted geocoded file...
^CTraceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/util.py", line 262, in _run_finalizers
    finalizer()
  File "/usr/lib/python3.6/multiprocessing/util.py", line 186, in __call__
    res = self._callback(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/shutil.py", line 480, in rmtree
    _rmtree_safe_fd(fd, path, onerror)
  File "/usr/lib/python3.6/shutil.py", line 438, in _rmtree_safe_fd
    onerror(os.unlink, fullname, sys.exc_info())
  File "/usr/lib/python3.6/shutil.py", line 436, in _rmtree_safe_fd
    os.unlink(name, dir_fd=topfd)
OSError: [Errno 16] Device or resource busy: '.nfs000000000efbb3e900000fca'
^[[A^C
```
seems to have started with addition of geolocation stuff
cc @paramt any thoughts?

**Comment by paramt** [comment]
Hmm... I have no idea why that is happening. Maybe we should use a different library for this feature?

**Comment by RDIL** [comment]
I think so.

**Comment by RDIL** [comment]
This only happens on runs where +iss has been used. It is definitely that geo lib.

**Comment by RDIL** [comment]
Oh well, doesn't matter that much.  I'll go ahead and close.
